### ISSUE TITLE
More than 1000 files installed for this component

### ISSUE THREAD

**Issue by divyayogesh** [alijaya/iron-accordions#1]
Hi,
When i do bower install of this component, it installed more than 1000 file.Inside the components/ folder  I could see some repeated components like iron-ajax,iron-icon etc. Are they all mandatory ? or can add it in /.gitignore.

Thanks,

**Comment by alijaya** [comment]
Ah... I'm sorry... it was a mistake... ._., the components folder is not necessary for this components... it's for the gh-pages only. I will remove it :D... thanks
