### ISSUE TITLE
Nested custom tag appears in the header

### ISSUE THREAD

**Issue by danielvanmil** [alijaya/iron-accordions#2]
When I nest a custom tag (like paper-button) for example as an element (not the first), then the element gets rendered in the header. Apparently the *:first-child selector in the iron-accordion also sees this element as the first element of it's parent? Can this be fixed by using a more specific selector?

For example:

```
<iron-accordions>
  <iron-accordion>
    <h3>myheader</h3>
    <paper-item>myItem</paper-item>
  </iron-accordion>
  <iron-accordion>
    <h3>myheader</h3>
    <paper-item>myItem</paper-item>
  </iron-accordion>
</iron-accordions>
```

**Comment by danielvanmil** [comment]
Looks like the spec regarding node distribution is not completely final and clear. It looks like :first-child is not supported anymore and also some selectors seem to work different in shady vs shadow dom. So the best option would be to use a (class) selector like "header" for this that is supported as far as I can see. This seems to work for custom elements and within shady and shadow dom.

**Comment by alijaya** [comment]
So you're suggesting to use class selector? Hmmm... I wonder if it works with *:nth-child(1)...

**Comment by alijaya** [comment]
i have tried it... neither *:first-child nor *:nth-child(1) worked... So i will use [header] selector, thanks :D
