### ISSUE TITLE
Not working with shadow dom

### ISSUE THREAD

**Issue by craftyc0der** [alijaya/iron-accordions#4]
If you configure polymer with shadow DOM rather than shady DOM this control doesn't work. Thoughts?

sad
`window.Polymer = {lazyRegister: true, dom: 'shadow'};`
happy
`window.Polymer = {lazyRegister: true, dom: 'shady'};`

**Comment by alijaya** [comment]
Sorry for late reply... I'll look into it

**Comment by alijaya** [comment]
Sorry for late reply... I'll look into it

**Comment by alijaya** [comment]
Hey... actually I have tackled this issue, but forgot to make the release version... so if you install from bower, it will use the old one. But I have made the release... so if you could upgrade the code, it would fix everything. But there's a catch, make sure you double check the documentation.

Here is the sample usage.
http://codepen.io/alijaya/pen/vKOVyQ

**Comment by craftyc0der** [comment]
I rolled my own, but I'll definitely try it another time.

**Comment by craftyc0der** [comment]
Thank you!
