### ISSUE TITLE
Feature: Provide method or event to collapse accordion

### ISSUE THREAD

**Issue by robertop87** [alijaya/iron-accordions#6]
I think the current behavior is OK, but in many cases the header would have button or any other interactive elements, then would be great has a mechanism to fire the collapse event from a specific element into the header

**Comment by alijaya** [comment]
hey... nice idea... :D... if you could give a pull request, i would gladly accept it :D

**Comment by alijaya** [comment]
for a second thought, you can change properties of iron-accordions.activateEvent to any event do you like, basically it's inherited from Polymer.IronMultiSelectableBehavior, so it should worked
